### PR TITLE
Fix git tag group ignore git tag prefix issue - #357

### LINKED ISSUE #357: `--tag-prefix` doesn't work for git tag group
**Describe the bug**
yor version 0.1.170 on Windows

**To Reproduce**
1. git clone https://github.com/Azure/terraform-azurerm-network.git
2. cd terraform-azurerm-network
3. Run cli command  'yor tag -d ${pwd} -skip-dirs /examples -tag-prefix my_tags_'

The generated tags were:

```hcl
tags = merge(var.tags, {
    git_commit           = "c506f86f75a34ad34c2b4437e8076f1f06bf6a00"
    git_file             = "main.tf"
    git_last_modified_at = "2022-11-23 09:20:55"
    git_last_modified_by = "xxx@hotmail.com"
    git_org              = "Azure"
    git_repo             = "terraform-azurerm-network"
    my_tags_yor_trace    = "be5dacae-bd25-4e94-bcaa-40eb839d953e"
  })
```

**Expected behavior**
All `git_xxx` tags should contains `my_tags_` prefix.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Yor Version 0.1.170

**Additional context**
Add any other context about the problem here (e.g. code snippets).

### PR DESCRIPTION
**Pull request by lonegunmanb**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

This pr should fix #357.

### CODE REVIEW

**Comment by lonegunmanb** [comment]
Hi @nimrodkor, we'd like to use `yor` in our projects but we've encountered some bugs, would you please review this pr when you have time? Thanks!

**Comment by lonegunmanb** [comment]
Hello? Is this project still actively maintained?

**Review by gruebel — APPROVED** [review]
thanks, looks good 💪 Will request a second review from a colleague

**Review by omryMen — APPROVED** [review]

**Comment by nimrodkor** [comment]
Sorry for the long response times, it's been holiday season with some extra vacation here :) @lonegunmanb

**Comment by lonegunmanb** [comment]
> Sorry for the long response times, it's been holiday season with some extra vacation here :) @lonegunmanb 

Nice! I've created a tool named [`yorbox`](https://github.com/lonegunmanb/yorbox) which I believe can be used along with `yor` in our projects. `yor` would be a vital part of our modules, thank you for your great job!

**Pull request merged**
